spring.application.name=sanatatea-noastra-frontend
server.port=${PORT:8080}
spring.thymeleaf.cache=true

# URL-ul backend-ului pe Railway ? il completam dupa deploy
backend.url=${BACKEND_URL:http://localhost:8081}
jwt.secret=HospiHelpSecretKey2026SuperLungSiComplicatPentruSiguranta
server.forward-headers-strategy=native